# lista przekleństw

swears <- c("fuck", "ass", "whore", "fucking", "slut", "shit", "bitch", "bullshit", "asshole", "damn",
                      "bastard", "dick", "minger", "munter", "pissed", "motherfucker", "bugger", "bollocks", 
                      "arse", "balls", "bint", "git", "crap", "cock", "dickhead", "dyke", "frigger", "goddamn", 
                      "hell", "kike", "nigga", "prick", "pussy", "shite", "spastic", "turd", "twat", "wanker",
                      "choad", "crickey", "shag", "cunt", "cocksucker", "tits", "bellend", "Fuck", "Ass", "Whore", 
                      "cumbubble", "fucktrumpet", "knobhead", "pissflaps", "shitbag", "cocknose", "dickweed", "bitchtits",
                      "arsebadger", "jizzcock", "boabby", "cumdumpster", "wanker", "twatwaffle", "thundercunt", "dickhead",
                      "pish", "shitpouch", "nonce", "jizzstain", "pisskidney", "wazzock", "fanny", "cumwipe",
                      "bellend", "pisswizard", "knobjockey", "cuntpuddle", "dickweasel", "quim", "bawbag", "fuckwit",
                      "tosspot", "cockwomble", "twatface", "cack", "fucknugget", "knobber", "arsehole", "fuckbucket",
                      "pillock", "fuckface", "shitmagnet", "bumhole", "shite", "scrote", "cuntflaps","tosser", "flange",
                      "slag", "arsebastard", "clunge", "dickfucker", "fannyflaps", "wankface", "shithouse", "knobcheese",
                      "gobshite", "jizzbreath", "todger", "pissartist", "douchecanoe", "nutsack", "arsewipe", "choad",
                      "clusterfuck", "cockburger", "arseclown", "fuckstick", "peckerhead", "rimjob", "schlong", "shitcunt",
                      "smeghead", "fuckshitter", "jizzmuffin", "shitspitter", "knobend", "prick", "bollockface", "bell", 
                      "shitnubbin", "wingnut", "fud", "jebend", "whalluper", "dickcheese", "pissbucket", "buttmunch", "shitlicker",
                      "bumder", "arsegoblin", "dickbag", "arsebutter", "bitches" , "Blow Job" , "blowjob" , "boffing" , "boiolas", 
                      "boobs" , "buceta" , "butt-pirate",  "butthole" , "cabron" , "cawk" , "cawks" , "chink",  
                      "cunts",  "dildo"  , "dildos",  "dominatrix" , "dyke",    "fag" , "fagit", "fags"  ,"feces"  ,  "feg",          
                      "flipping the bird", "Fudge Packer"  , "God-damned", "gook" , "injun"  ,"jackoff",  "jap" , "japs", 
                      "jerk-off" , "kawk" , "kuk"  ,  "kunt" ,  "kunts" , "kuntz" , "massterbait",      "masstrbait"  ,  "masterbaiter" ,
                      "mibun" , "Motha Fucker",  "motherfucker" , "orafis" , "oriface" , "orifice" , "orifiss" , "packy", "pecker" ,
                      "phuck"    , "pimmel" , "pusse", "puto"  , "recktum", "rectum" ,  "scank", "screw" , "screwing",  "Shity" ,  
                      "skanks"  , "Slutty" , "wank"  , "xrated", "abeed"  , "abid", "africoon"  , "alligator bait" , "arabush" , "arabushs" ,
                      "armo", "armos"  , "beanbag",  "boche" ,"boches",  "whigger", "whiggers" ,"white trash", "whitey","whities" 
                      , "wigga" , "wiggas"  , "wigger" , "wog", "assmuncher" , "assnigger", "asspacker", "asspirate", "assrammer", "flamer" , "flange",
                      "bastard", "bastards", "piss", "nigger", "fudgepacker", "fuck off", "piss off", "suck my dick", "eat shit", "knob")
